"""Generate Python lookup tables from the upstream Rust sources.

The upstream project keeps three large static tables in Rust source files.
They are pure data, so translating them mechanically is both faster and safer
than hand-porting:

    src/glyph_names.rs   -> pdf_inspector/_glyph_names_data.py
    src/adobe_korea1.rs  -> pdf_inspector/_adobe_korea1_data.py

Run from the repo root::

    python tools/codegen_tables.py /path/to/upstream/pdf-inspector

The generated files are committed, so this script only needs to run when the
upstream tables change.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# ── glyph_names.rs ───────────────────────────────────────────────────

# Matches: m.insert("name", 'X');  where X is a Rust char literal.
GLYPH_LINE = re.compile(r"""^\s*m\.insert\("([^"]+)",\s*'(.*)'\);\s*$""")

# Rust char escapes that appear in the upstream table.
RUST_CHAR_ESCAPES = {
    r"\\": "\\",
    r"\'": "'",
    r"\"": '"',
    r"\n": "\n",
    r"\r": "\r",
    r"\t": "\t",
    r"\0": "\0",
}

RUST_UNICODE_ESCAPE = re.compile(r"^\\u\{([0-9A-Fa-f]+)\}$")
RUST_HEX_ESCAPE = re.compile(r"^\\x([0-9A-Fa-f]{2})$")


def decode_rust_char(literal: str) -> str:
    """Decode the body of a Rust char literal into a single Python character."""
    if literal in RUST_CHAR_ESCAPES:
        return RUST_CHAR_ESCAPES[literal]
    m = RUST_UNICODE_ESCAPE.match(literal)
    if m:
        return chr(int(m.group(1), 16))
    m = RUST_HEX_ESCAPE.match(literal)
    if m:
        return chr(int(m.group(1), 16))
    if len(literal) == 1:
        return literal
    raise ValueError(f"unrecognised Rust char literal: {literal!r}")


def gen_glyph_names(rust_src: Path, out: Path) -> int:
    entries: list[tuple[str, str]] = []
    for line in rust_src.read_text(encoding="utf-8").splitlines():
        m = GLYPH_LINE.match(line)
        if m:
            entries.append((m.group(1), decode_rust_char(m.group(2))))

    if not entries:
        raise SystemExit(f"no glyph entries found in {rust_src}")

    lines = [
        '"""Adobe Glyph List name -> Unicode character.',
        "",
        "Generated by tools/codegen_tables.py from upstream src/glyph_names.rs.",
        'Do not edit by hand."""',
        "",
        "GLYPH_TO_UNICODE: dict[str, str] = {",
    ]
    for name, char in entries:
        lines.append(f"    {name!r}: {char!r},")
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    return len(entries)


# ── adobe_korea1.rs ──────────────────────────────────────────────────

# Matches: (1, 0x0020),
KOREA1_LINE = re.compile(r"^\s*\((\d+),\s*0x([0-9A-Fa-f]+)\),\s*$")


def gen_adobe_korea1(rust_src: Path, out: Path) -> int:
    entries: list[tuple[int, int]] = []
    for line in rust_src.read_text(encoding="utf-8").splitlines():
        m = KOREA1_LINE.match(line)
        if m:
            entries.append((int(m.group(1)), int(m.group(2), 16)))

    if not entries:
        raise SystemExit(f"no Adobe-Korea1 entries found in {rust_src}")

    # Upstream stores a CID-sorted slice and binary-searches it. A dict is the
    # idiomatic Python equivalent and is O(1); the sort order carries no other
    # meaning, so nothing is lost.
    lines = [
        '"""Adobe-Korea1 CID -> Unicode codepoint.',
        "",
        "Generated by tools/codegen_tables.py from upstream src/adobe_korea1.rs,",
        "which in turn derives from adobe-type-tools/cmap-resources",
        "Adobe-Korea1-2/cid2code.txt (UniKS-UCS2 column, first mapping per CID).",
        'Do not edit by hand."""',
        "",
        "ADOBE_KOREA1_CID_TO_UNICODE: dict[int, int] = {",
    ]
    for cid, uni in entries:
        lines.append(f"    {cid}: 0x{uni:04X},")
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    return len(entries)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    upstream = Path(sys.argv[1])
    pkg = Path(__file__).resolve().parent.parent / "src" / "pdf_inspector"

    n_glyphs = gen_glyph_names(
        upstream / "src" / "glyph_names.rs", pkg / "_glyph_names_data.py"
    )
    n_korea1 = gen_adobe_korea1(
        upstream / "src" / "adobe_korea1.rs", pkg / "_adobe_korea1_data.py"
    )
    print(f"glyph names: {n_glyphs}")
    print(f"adobe-korea1: {n_korea1}")


if __name__ == "__main__":
    main()
